### ISSUE TITLE
ask for detail

### ISSUE THREAD

**Issue by monib110** [harshiitsingh/Flipkart-Grid-5.0#1]
Hello.
I have a question... Is this framework completed?
I mean It really generate recommendations by stable diffusion?

Is there any article that explains details?

**Comment by harshiitsingh** [comment]
Hi @monib110 
This project is currently a work in progress and has several unresolved issues. It is not yet fully functional in terms of generating stable recommendations through diffusion. Although it generates images based on prompts, the output is not as accurate.

I would suggest to follow these articles:
https://jalammar.github.io/illustrated-stable-diffusion/

https://nn.labml.ai/diffusion/stable_diffusion/latent_diffusion.html

https://www.tensorflow.org/tutorials/generative/generate_images_with_stable_diffusion
